import { Component, effect, ElementRef, inject, signal, viewChild, WritableSignal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Message } from '../interfaces/message';
import { ChatService } from '../services/chat/chat.service';

/**
 * Interface for a single chat message.
 */

@Component({
  selector: 'app-chat',
  imports: [FormsModule],
  templateUrl: './chat.html',
  styleUrl: './chat.scss',
})
export class Chat {
  // Signals for managing chat state
  history: WritableSignal<Message[]> = signal([]);
  loading: WritableSignal<boolean> = signal(false);
  error: WritableSignal<any> = signal(null);
  message: WritableSignal<string> = signal('');

  private chatContainer = viewChild<ElementRef<HTMLDivElement>>('chatContainer');

  private chatService = inject(ChatService);

  constructor() {
    effect(() => {
      if (this.history().length > 0) this.scrollToBottom();
    });
  }

   private scrollToBottom(): void {
    const container = this.chatContainer();

    if (container) {
      // We use a small timeout to ensure that the DOM has been updated
      // with the new message before we try to scroll.
      setTimeout(
        () => (container.nativeElement.scrollTop = container.nativeElement.scrollHeight),
        0
      );
    }
  }

  /**
   * Sends a message from the user and simulates a bot response.
   */
  sendMessage(): void {
    const userMessage = this.message().trim();
    if (!userMessage || this.loading()) {
      return;
    }

    const newMessage: Message = {
      id: Date.now(),
      sender: 'user',
      message: userMessage,
    };

    // Add user message to history and clear input
    this.history.update((currentHistory) => [...currentHistory, newMessage]);
    this.message.set('');

    this.askLLM(newMessage);
  }

  async askLLM(message: Message): Promise<void> {
    try {
      this.loading.set(true);
      this.error.set(null);

      // get response from LLM (simulated here)
      const botMessage = await this.chatService.sendMessageToLLM(message?.message);

      // const botMessage =
      //   'This is a test bot message generated by Jason.';

      const newBotMessage: Message = {
        id: Date.now(),
        sender: 'bot',
        message: botMessage,
      };

      // Simulate bot response after a short delay
      // setTimeout(() => {
      //   // Add bot message to history
      //   this.history.update((currentHistory) => [...currentHistory, newBotMessage]);
      //   this.loading.set(false);
      // }, 1500);

      // Add bot message to history
      this.history.update((currentHistory) => [...currentHistory, newBotMessage]);
    } catch (error: any) {
      console.error('Error communicating with LLM:', error);
      this.error.set(error?.message);
    } finally {
      this.loading.set(false);
    }
  }
}
